services:
  - type: web
    name: laravel-aiven-app
    env: docker
    plan: free
    branch: main
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate --force
      php artisan migrate --force
      php artisan storage:link
    startCommand: |
      php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        sync: false  # Render sẽ yêu cầu bạn nhập key hoặc sẽ generate khi build
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: financial-management-camlee05.l.aivencloud.com
      - key: DB_PORT
        value: 12284
      - key: DB_DATABASE
        value: defaultdb
      - key: DB_USERNAME
        value: avnadmin
      - key: DB_PASSWORD
        value: AVNS_jY80voOIHHVgm2boQs4
      - key: DB_URI
        value: mysql://avnadmin:AVNS_jY80voOIHHVgm2boQs4@financial-management-camlee05.l.aivencloud.com:12284/defaultdb?ssl-mode=REQUIRED
